version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=${DB_USER}", "--password=${DB_PASSWORD}", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

  backend:
    image: ivang0nzalez/backend-movies-image:v1
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./django/.env

  frontend:
    image: ivang0nzalez/frontend-movies-image:v1
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./front-end/.env.local

volumes:
  db_data:
